// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2ly6r9Wy7b1TFRsFerAMtMX2TmZy4Owo',
    appId: '1:326836314760:web:4f54ac076ba5e51d46753d',
    messagingSenderId: '326836314760',
    projectId: 'flutterproject-5a176',
    authDomain: 'flutterproject-5a176.firebaseapp.com',
    storageBucket: 'flutterproject-5a176.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZGWRTS_VpfILzwLKz4BExxEeEZ7YU42w',
    appId: '1:326836314760:ios:11dd3e5d6719f8c146753d',
    messagingSenderId: '326836314760',
    projectId: 'flutterproject-5a176',
    storageBucket: 'flutterproject-5a176.firebasestorage.app',
    iosBundleId: 'com.example.sodaDiopL3glExamen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZGWRTS_VpfILzwLKz4BExxEeEZ7YU42w',
    appId: '1:326836314760:ios:11dd3e5d6719f8c146753d',
    messagingSenderId: '326836314760',
    projectId: 'flutterproject-5a176',
    storageBucket: 'flutterproject-5a176.firebasestorage.app',
    iosBundleId: 'com.example.sodaDiopL3glExamen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2ly6r9Wy7b1TFRsFerAMtMX2TmZy4Owo',
    appId: '1:326836314760:web:71d3123f9458a29746753d',
    messagingSenderId: '326836314760',
    projectId: 'flutterproject-5a176',
    authDomain: 'flutterproject-5a176.firebaseapp.com',
    storageBucket: 'flutterproject-5a176.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb4_TgrWZikvv9aaBXOjwWm9znpDDadaU',
    appId: '1:326836314760:android:a241d64310be9e5246753d',
    messagingSenderId: '326836314760',
    projectId: 'flutterproject-5a176',
    storageBucket: 'flutterproject-5a176.firebasestorage.app',
  );

}