// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWLvVG_6W2l5iqNx8KrBcRUN7BGm96Z04',
    appId: '1:577962529704:web:530151559673817b5ec39d',
    messagingSenderId: '577962529704',
    projectId: 'examenflutter-5f312',
    authDomain: 'examenflutter-5f312.firebaseapp.com',
    storageBucket: 'examenflutter-5f312.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw5eazD6DEdkN6sKbhUSLH8c-DAaVtIkg',
    appId: '1:577962529704:android:b003c1b0669502d55ec39d',
    messagingSenderId: '577962529704',
    projectId: 'examenflutter-5f312',
    storageBucket: 'examenflutter-5f312.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAE1S3DTVOaGcBLrOObwxMadVasdoB07w',
    appId: '1:577962529704:ios:78cd6791a392d3645ec39d',
    messagingSenderId: '577962529704',
    projectId: 'examenflutter-5f312',
    storageBucket: 'examenflutter-5f312.firebasestorage.app',
    iosBundleId: 'com.example.examenSodaDiopL3gl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAE1S3DTVOaGcBLrOObwxMadVasdoB07w',
    appId: '1:577962529704:ios:78cd6791a392d3645ec39d',
    messagingSenderId: '577962529704',
    projectId: 'examenflutter-5f312',
    storageBucket: 'examenflutter-5f312.firebasestorage.app',
    iosBundleId: 'com.example.examenSodaDiopL3gl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWLvVG_6W2l5iqNx8KrBcRUN7BGm96Z04',
    appId: '1:577962529704:web:f76a64d15aeec55d5ec39d',
    messagingSenderId: '577962529704',
    projectId: 'examenflutter-5f312',
    authDomain: 'examenflutter-5f312.firebaseapp.com',
    storageBucket: 'examenflutter-5f312.firebasestorage.app',
  );
}
